
var Stockfish = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Stockfish) {
  Stockfish = Stockfish || {};


null;var d;d||(d=typeof Stockfish !== 'undefined' ? Stockfish : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});d.postCustomMessage=a=>{for(let b of l.Ca)b.postMessage({cmd:"custom",userData:a})};class ca{constructor(){this.Ha=null;this.Za=[]}async get(){return 0<this.Za.length?this.Za.shift():await new Promise(a=>this.Ha=a)}put(a){this.Ha?(this.Ha(a),this.Ha=null):this.Za.push(a)}}d.queue=new ca;d.onCustomMessage=a=>{d.queue.put(a)};d.postMessage=d.postCustomMessage;
const da=[];d.addMessageListener=a=>{da.push(a)};d.removeMessageListener=a=>{a=da.indexOf(a);0<=a&&da.splice(a,1)};d.print=d.printErr=a=>{if(0===da.length)console.log(a);else for(let b of da)b(a)};d.terminate=()=>{l.Wa()};var ea={},m;for(m in d)d.hasOwnProperty(m)&&(ea[m]=d[m]);var fa=[],ha="./this.program";function ia(a,b){throw b;}
var ja="object"===typeof window,n="function"===typeof importScripts,ka="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,q=d.ENVIRONMENT_IS_PTHREAD||!1,z="";function la(a){return d.locateFile?d.locateFile(a,z):z+a}var ma,na,oa,pa;
if(ka){z=n?require("path").dirname(z)+"/":__dirname+"/";ma=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return oa.readFileSync(a,b?null:"utf8")};na=function(a){a=ma(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ha=process.argv[1].replace(/\\/g,"/"));fa=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof qa))throw a;});process.on("unhandledRejection",A);ia=function(a,b){if(ra())throw process.exitCode=
a,b;process.exit(a)};d.inspect=function(){return"[Emscripten Module object]"};var sa;try{sa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=sa.Worker}else if(ja||n)n?z=self.location.href:"undefined"!==typeof document&&document.currentScript&&(z=document.currentScript.src),_scriptDir&&(z=_scriptDir),0!==z.indexOf("blob:")?z=z.substr(0,z.lastIndexOf("/")+1):z="",ka?(ma=
function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return oa.readFileSync(a,b?null:"utf8")},na=function(a){a=ma(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));
ka&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ta=d.print||console.log.bind(console),B=d.printErr||console.warn.bind(console);for(m in ea)ea.hasOwnProperty(m)&&(d[m]=ea[m]);ea=null;d.arguments&&(fa=d.arguments);d.thisProgram&&(ha=d.thisProgram);d.quit&&(ia=d.quit);var ua,va;d.wasmBinary&&(va=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var E,wa,ya=!1,za;
function assert(a,b){a||A("Assertion failed: "+b)}function Aa(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Ba="undefined"!==typeof TextDecoder?new Aa("utf8"):void 0;
function Ca(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(e="";b<c;){var h=a[b++];if(h&128){var g=a[b++]&63;if(192==(h&224))e+=String.fromCharCode((h&31)<<6|g);else{var k=a[b++]&63;h=224==(h&240)?(h&15)<<12|g<<6|k:(h&7)<<18|g<<12|k<<6|a[b++]&63;65536>h?e+=String.fromCharCode(h):(h-=65536,e+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else e+=String.fromCharCode(h)}return e}function F(a){return a?Ca(G,a,void 0):""}
function I(a,b,c,e){if(0<e){e=c+e-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var k=a.charCodeAt(++h);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=e)break;b[c++]=g}else{if(2047>=g){if(c+1>=e)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=e)break;b[c++]=224|g>>12}else{if(c+3>=e)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}
function Da(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Aa("utf-16le");function Fa(a){var b=Da(a)+1,c=Ga(b);I(a,K,c,b);return c}var Ha,K,G,L,M,N,Ia;q&&(Ha=d.buffer);var Ja=d.INITIAL_MEMORY||1073741824;
if(q)E=d.wasmMemory,Ha=d.buffer;else if(d.wasmMemory)E=d.wasmMemory;else if(E=new WebAssembly.Memory({initial:Ja/65536,maximum:Ja/65536,shared:!0}),!(E.buffer instanceof SharedArrayBuffer))throw B("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ka&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");E&&(Ha=E.buffer);Ja=Ha.byteLength;var Q=Ha;Ha=Q;d.HEAP8=K=new Int8Array(Q);d.HEAP16=new Int16Array(Q);d.HEAP32=M=new Int32Array(Q);d.HEAPU8=G=new Uint8Array(Q);d.HEAPU16=L=new Uint16Array(Q);d.HEAPU32=N=new Uint32Array(Q);d.HEAPF32=new Float32Array(Q);d.HEAPF64=Ia=new Float64Array(Q);var Ka=[],La=[],Ma=[],Na=[],R=0;function ra(){return noExitRuntime||0<R}function Oa(){var a=d.preRun.shift();Ka.unshift(a)}var Pa=0,Qa=null,Ra=null;
function Sa(){Pa++;d.monitorRunDependencies&&d.monitorRunDependencies(Pa)}function Ta(){Pa--;d.monitorRunDependencies&&d.monitorRunDependencies(Pa);if(0==Pa&&(null!==Qa&&(clearInterval(Qa),Qa=null),Ra)){var a=Ra;Ra=null;a()}}d.preloadedImages={};d.preloadedAudios={};function A(a){if(d.onAbort)d.onAbort(a);assert(!q);B(a);ya=!0;za=1;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}
function Ua(){return S.startsWith("data:application/octet-stream;base64,")}var S;S="stockfish.wasm";Ua()||(S=la(S));function Va(){var a=S;try{if(a==S&&va)return new Uint8Array(va);if(na)return na(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Wa(){return va||!ja&&!n||"function"!==typeof fetch?Promise.resolve().then(function(){return Va()}):fetch(S,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+S+"'";return a.arrayBuffer()}).catch(function(){return Va()})}var Xa={28087:function(){throw"Canceled!";}};
function Ya(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.ab;"number"===typeof c?void 0===b.Ia?dynCall_v.call(null,c):dynCall_vi.apply(null,[c,b.Ia]):c(void 0===b.Ia?null:b.Ia)}}}
function Za(a,b){if(0>=a||a>K.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(M,$a>>2),e=0;if(c==a&&Atomics.compareExchange(M,$a>>2,c,0)==c&&(--b,e=1,0>=b))return 1;a=Atomics.notify(M,a>>2,b);if(0<=a)return a+e;throw"Atomics.notify returned an unexpected value "+a;}d._emscripten_futex_wake=Za;
function ab(a){if(q)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=l.Aa[a];b&&(M[a+12>>2]=0,l.Pa(b.worker))}
var l={Da:[],Ca:[],Ya:[],Lb:function(){},nb:function(){for(var a=T(228),b=0;57>b;++b)N[a/4+b]=0;M[a+12>>2]=a;b=a+152;M[b>>2]=b;var c=T(512);for(b=0;128>b;++b)N[c/4+b]=0;Atomics.store(N,a+100>>2,c);Atomics.store(N,a+40>>2,a);bb(a,!n,1);cb(a)},ob:function(){l.receiveObjectTransfer=l.tb;l.threadInit=l.yb;l.threadCancel=l.xb;l.threadExit=l.gb;l.setExitStatus=l.vb},Aa:{},Xa:[],eb:function(){for(;0<l.Xa.length;)l.Xa.pop()();db()},fb:function(a,b){Atomics.store(N,a+56>>2,1);Atomics.store(N,a+60>>2,0);l.eb();
Atomics.store(N,a+4>>2,b);Atomics.store(N,a+0>>2,1);Za(a+0,2147483647);bb(0,0,0)},vb:function(a){za=a},gb:function(a){var b=eb();b&&(l.fb(b,a),q&&postMessage({cmd:"exit"}))},xb:function(){l.fb(eb(),-1);postMessage({cmd:"cancelDone"})},Wa:function(){for(var a in l.Aa){var b=l.Aa[a];b&&b.worker&&l.Pa(b.worker)}l.Aa={};for(a=0;a<l.Da.length;++a){var c=l.Da[a];c.terminate()}l.Da=[];for(a=0;a<l.Ca.length;++a)c=l.Ca[a],b=c.za,l.Ua(b),c.terminate();l.Ca=[]},Ua:function(a){if(a){if(a.Ba){var b=M[a.Ba+100>>
2];M[a.Ba+100>>2]=0;fb(b);fb(a.Ba)}a.Ba=0;a.Ta&&a.Ea&&fb(a.Ea);a.Ea=0;a.worker&&(a.worker.za=null)}},Pa:function(a){l.ub(function(){delete l.Aa[a.za.Ba];l.Da.push(a);l.Ca.splice(l.Ca.indexOf(a),1);l.Ua(a.za);a.za=void 0})},ub:function(a){M[gb>>2]=0;try{a()}finally{M[gb>>2]=1}},tb:function(){},yb:function(){for(var a in l.Ya)l.Ya[a]()},qb:function(a,b){a.onmessage=function(c){var e=c.data,h=e.cmd;a.za&&(l.jb=a.za.Ba);if(e.targetThread&&e.targetThread!=eb()){var g=l.Aa[e.Rb];g?g.worker.postMessage(c.data,
e.transferList):B('Internal error! Worker sent a message "'+h+'" to target pthread '+e.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===h)hb();else if("spawnThread"===h)ib(c.data);else if("cleanupThread"===h)ab(e.thread);else if("killThread"===h){c=e.thread;if(q)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";M[c+12>>2]=0;e=l.Aa[c];delete l.Aa[c];e.worker.terminate();
l.Ua(e);l.Ca.splice(l.Ca.indexOf(e.worker),1);e.worker.za=void 0}else if("cancelThread"===h){c=e.thread;if(q)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";l.Aa[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===h)a.loaded=!0,b&&b(a),a.Ja&&(a.Ja(),delete a.Ja);else if("print"===h)ta("Thread "+e.threadId+": "+e.text);else if("printErr"===h)B("Thread "+e.threadId+": "+e.text);else if("alert"===
h)alert("Thread "+e.threadId+": "+e.text);else if("exit"===h)a.za&&Atomics.load(N,a.za.Ba+64>>2)&&l.Pa(a);else if("exitProcess"===h)try{jb(e.returnCode)}catch(k){if(k instanceof qa)return;throw k;}else"cancelDone"===h?l.Pa(a):"objectTransfer"!==h&&("setimmediate"===c.data.target?a.postMessage(c.data):B("worker sent an unknown command "+h));l.jb=void 0};a.onerror=function(c){B("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};ka&&(a.on("message",function(c){a.onmessage({data:c})}),
a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:d.mainScriptUrlOrBlob||_scriptDir,wasmMemory:E,wasmModule:wa})},hb:function(){var a=la("stockfish.worker.js");l.Da.push(new Worker(a))},lb:function(){0==l.Da.length&&(l.hb(),l.qb(l.Da[0]));return l.Da.pop()},Eb:function(a){for(a=performance.now()+a;performance.now()<a;);}};d.establishStackSpace=function(a,b){kb(a,b);lb(a)};d.invokeEntryPoint=function(a,b){return mb.apply(null,[a,b])};var nb;
nb=ka?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:q?function(){return performance.now()-d.__performance_now_clock_drift}:function(){return performance.now()};
function ib(a){if(q)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=l.lb();if(!b)return 6;if(void 0!==b.za)throw"Internal error!";if(!a.Oa)throw"Internal error, no pthread ptr!";l.Ca.push(b);for(var c=T(512),e=0;128>e;++e)M[c+4*e>>2]=0;var h=a.Ea+a.Fa;e=l.Aa[a.Oa]={worker:b,Ea:a.Ea,Fa:a.Fa,Ta:a.Ta,Ba:a.Oa};var g=e.Ba>>2;Atomics.store(N,g+16,a.detached);Atomics.store(N,g+25,c);Atomics.store(N,g+10,e.Ba);Atomics.store(N,g+20,a.Fa);Atomics.store(N,g+19,
h);Atomics.store(N,g+26,a.Fa);Atomics.store(N,g+28,h);Atomics.store(N,g+29,a.detached);c=ob()+40;Atomics.store(N,g+43,c);b.za=e;var k={cmd:"run",start_routine:a.wb,arg:a.Ia,threadInfoStruct:a.Oa,stackBase:a.Ea,stackSize:a.Fa};b.Ja=function(){k.time=performance.now();b.postMessage(k,a.Db)};b.loaded&&(b.Ja(),delete b.Ja);return 0}
function pb(a,b,c){if(0>=a||a>K.length||a&1)return-28;if(ja){if(Atomics.load(M,a>>2)!=b)return-6;var e=performance.now();c=e+c;for(Atomics.exchange(M,$a>>2,a);;){e=performance.now();if(e>c)return Atomics.exchange(M,$a>>2,0),-73;e=Atomics.exchange(M,$a>>2,0);if(0==e)break;hb();if(Atomics.load(M,a>>2)!=b)return-6;Atomics.exchange(M,$a>>2,a)}return 0}a=Atomics.wait(M,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function qb(){ka||n||(ua||(ua={}),ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,B("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function rb(a,b){if(!a)return B("pthread_join attempted on a null thread pointer!"),71;if(q&&eb()==a)return B("PThread "+a+" is attempting to join to itself!"),16;if(!q&&sb()==a)return B("Main thread "+a+" is attempting to join to itself!"),16;if(M[a+12>>2]!==a)return B("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(N,a+64>>2))return B("Attempted to join thread "+a+", which was already detached!"),28;for(qb();;){var c=
Atomics.load(N,a>>2);if(1==c)return c=Atomics.load(N,a+4>>2),b&&(M[b>>2]=c),Atomics.store(N,a+64>>2,1),q?postMessage({cmd:"cleanupThread",thread:a}):ab(a),0;tb();q||hb();pb(a,c,q?100:1)}}var ub={},vb=[null,[],[]],wb={};function xb(a,b,c){return q?U(2,1,a,b,c):0}function yb(a,b){if(q)return U(3,1,a,b)}function zb(a,b,c){return q?U(4,1,a,b,c):0}
function Ab(a,b,c,e,h,g){if(q)b=U(5,1,a,b,c,e,h,g);else if(g<<=12,0!==(e&16)&&0!==a%65536)b=-28;else if(0!==(e&32)){a=65536*Math.ceil(b/65536);var k=Bb(65536,a);k?(G.fill(0,k,k+a),a=k):a=0;a?(ub[a]={sb:a,pb:b,ib:!0,fd:h,Ob:c,flags:e,offset:g},b=a):b=-48}else b=-52;return b}function Cb(a,b){if(q)a=U(6,1,a,b);else{var c=ub[a];0!==b&&c?(b===c.pb&&(ub[a]=null,c.ib&&fb(c.sb)),a=0):a=-28}return a}function Db(a,b,c){if(q)return U(7,1,a,b,c)}function Eb(a,b){if(q)return U(8,1,a,b)}
function Fb(){if(q)return U(9,1);A()}var Gb=[];function Hb(a){if(q)return U(10,1,a);noExitRuntime=!1;R=0;jb(a)}function U(a,b){for(var c=arguments.length-2,e=Ib(),h=Ga(8*c),g=h>>3,k=0;k<c;k++)Ia[g+k]=arguments[2+k];c=Jb(a,c,h,b);lb(e);return c}var Kb=[],Lb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Mb(a){a=2<a?F(a):a;return Lb[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Nb(a,b,c){var e=Mb(a);if(!e)return-4;e.Na&&(M[e.Na>>2]=b,M[e.Na+4>>2]=c);if(e.cb||!e.Gb)e.cb&&(e=e.cb),a=!1,e.Ma&&e.Ma.La&&(a=e.Ma.La.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===e.width&&a[3]===e.height),e.width=b,e.height=c,a&&e.Ma.La.viewport(0,0,b,c);else{if(e.Na){e=M[e.Na+8>>2];a=a?F(a):"";var h=Ib(),g=Ga(12),k=0;if(a){k=Da(a)+1;var u=T(k);I(a,G,u,k);k=u}M[g>>2]=k;M[g+4>>2]=b;M[g+8>>2]=c;Ob(0,e,657457152,0,k,g);lb(h);return 1}return-4}return 0}
function Pb(a,b,c){return q?U(11,1,a,b,c):Nb(a,b,c)}function V(a,b){if(!ya)if(b)a();else{try{a()}catch(c){if(c instanceof qa)return;if("unwind"!==c)throw c&&"object"===typeof c&&c.stack&&B("exception thrown: "+[c,c.stack]),c;}if(q&&!ra())try{q?Qb(za):jb(za)}catch(c){if(!(c instanceof qa))throw c;}}}var Rb=[];function X(a,b){N[a>>2]=b;N[a+4>>2]=b/4294967296|0}
function Sb(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(e){b(e);return}c.onupgradeneeded=function(e){e=e.target.result;e.objectStoreNames.contains("FILES")&&e.deleteObjectStore("FILES");e.createObjectStore("FILES")};c.onsuccess=function(e){a(e.target.result)};c.onerror=function(e){b(e)}}var Tb;
function Ub(a,b,c,e,h){function g(C){var D=0,w=0;C&&(w=p.response?p.response.byteLength:0,D=T(w),G.set(new Uint8Array(p.response),D));N[a+12>>2]=D;X(a+16,w)}var k=N[a+8>>2];if(k){var u=F(k),t=a+112,v=F(t);v||(v="GET");var y=N[t+52>>2],O=N[t+56>>2],J=!!N[t+60>>2],f=N[t+68>>2],r=N[t+72>>2];k=N[t+76>>2];var x=N[t+80>>2],H=N[t+84>>2];t=N[t+88>>2];var P=!!(y&1),W=!!(y&2);y=!!(y&64);f=f?F(f):void 0;r=r?F(r):void 0;var Ea=x?F(x):void 0,p=new XMLHttpRequest;p.withCredentials=J;p.open(v,u,!y,f,r);y||(p.timeout=
O);p.Ha=u;p.responseType="arraybuffer";x&&p.overrideMimeType(Ea);if(k)for(;;){v=N[k>>2];if(!v)break;u=N[k+4>>2];if(!u)break;k+=8;v=F(v);u=F(u);p.setRequestHeader(v,u)}Rb.push(p);N[a+0>>2]=Rb.length;k=H&&t?G.slice(H,H+t):null;p.onload=function(C){g(P&&!W);var D=p.response?p.response.byteLength:0;X(a+24,0);D&&X(a+32,D);L[a+40>>1]=p.readyState;L[a+42>>1]=p.status;p.statusText&&I(p.statusText,G,a+44,64);200<=p.status&&300>p.status?b&&b(a,p,C):c&&c(a,p,C)};p.onerror=function(C){g(P);var D=p.status;X(a+
24,0);X(a+32,p.response?p.response.byteLength:0);L[a+40>>1]=p.readyState;L[a+42>>1]=D;c&&c(a,p,C)};p.ontimeout=function(C){c&&c(a,p,C)};p.onprogress=function(C){var D=P&&W&&p.response?p.response.byteLength:0,w=0;P&&W&&(w=T(D),G.set(new Uint8Array(p.response),w));N[a+12>>2]=w;X(a+16,D);X(a+24,C.loaded-D);X(a+32,C.total);L[a+40>>1]=p.readyState;3<=p.readyState&&0===p.status&&0<C.loaded&&(p.status=200);L[a+42>>1]=p.status;p.statusText&&I(p.statusText,G,a+44,64);e&&e(a,p,C);w&&fb(w)};p.onreadystatechange=
function(C){L[a+40>>1]=p.readyState;2<=p.readyState&&(L[a+42>>1]=p.status);h&&h(a,p,C)};try{p.send(k)}catch(C){c&&c(a,p,C)}}else c(a,0,"no url specified!")}
function Vb(a,b,c,e){var h=Tb;if(h){var g=N[a+112+64>>2];g||(g=N[a+8>>2]);var k=F(g);try{var u=h.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,k);u.onsuccess=function(){L[a+40>>1]=4;L[a+42>>1]=200;I("OK",G,a+44,64);c(a,0,k)};u.onerror=function(t){L[a+40>>1]=4;L[a+42>>1]=413;I("Payload Too Large",G,a+44,64);e(a,0,t)}}catch(t){e(a,0,t)}}else e(a,0,"IndexedDB not available!")}
function Wb(a,b,c){var e=Tb;if(e){var h=N[a+112+64>>2];h||(h=N[a+8>>2]);h=F(h);try{var g=e.transaction(["FILES"],"readonly").objectStore("FILES").get(h);g.onsuccess=function(k){if(k.target.result){k=k.target.result;var u=k.byteLength||k.length,t=T(u);G.set(new Uint8Array(k),t);N[a+12>>2]=t;X(a+16,u);X(a+24,0);X(a+32,u);L[a+40>>1]=4;L[a+42>>1]=200;I("OK",G,a+44,64);b(a,0,k)}else L[a+40>>1]=4,L[a+42>>1]=404,I("Not Found",G,a+44,64),c(a,0,"no data")};g.onerror=function(k){L[a+40>>1]=4;L[a+42>>1]=404;
I("Not Found",G,a+44,64);c(a,0,k)}}catch(k){c(a,0,k)}}else c(a,0,"IndexedDB not available!")}
function Xb(a,b,c){var e=Tb;if(e){var h=N[a+112+64>>2];h||(h=N[a+8>>2]);h=F(h);try{var g=e.transaction(["FILES"],"readwrite").objectStore("FILES").delete(h);g.onsuccess=function(k){k=k.target.result;N[a+12>>2]=0;X(a+16,0);X(a+24,0);X(a+32,0);L[a+40>>1]=4;L[a+42>>1]=200;I("OK",G,a+44,64);b(a,0,k)};g.onerror=function(k){L[a+40>>1]=4;L[a+42>>1]=404;I("Not Found",G,a+44,64);c(a,0,k)}}catch(k){c(a,0,k)}}else c(a,0,"IndexedDB not available!")}
function Yb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,h,g){b.drawArraysInstancedANGLE(c,e,h,g)},a.drawElementsInstanced=function(c,e,h,g,k){b.drawElementsInstancedANGLE(c,e,h,g,k)})}
function Zb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function $b(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}
function ac(a,b){a.bb||(a.bb=a.getContext,a.getContext=function(e,h){h=a.bb(e,h);return"webgl"==e==h instanceof WebGLRenderingContext?h:null});var c=a.getContext("webgl",b);return c?bc(c,b):0}function bc(a,b){var c=T(8);M[c+4>>2]=eb();var e={Kb:c,attributes:b,version:b.rb,La:a};a.canvas&&(a.canvas.Ma=e);("undefined"===typeof b.$a||b.$a)&&cc(e);return c}
function cc(a){a||(a=dc);if(!a.mb){a.mb=!0;var b=a.La;Yb(b);Zb(b);$b(b);b.Hb=b.getExtension("EXT_disjoint_timer_query");b.Nb=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var dc,ec=["default","low-power","high-performance"],fc={};
function gc(){if(!hc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ha||"./this.program"},b;for(b in fc)void 0===fc[b]?delete a[b]:a[b]=fc[b];var c=[];for(b in a)c.push(b+"="+a[b]);hc=c}return hc}var hc;
function ic(a,b){if(q)return U(12,1,a,b);var c=0;gc().forEach(function(e,h){var g=b+c;h=M[a+4*h>>2]=g;for(g=0;g<e.length;++g)K[h++>>0]=e.charCodeAt(g);K[h>>0]=0;c+=e.length+1});return 0}function jc(a,b){if(q)return U(13,1,a,b);var c=gc();M[a>>2]=c.length;var e=0;c.forEach(function(h){e+=h.length+1});M[b>>2]=e;return 0}function kc(a){return q?U(14,1,a):0}function lc(a,b){if(q)return U(15,1,a,b);a=1==a||2==a?2:A();K[b>>0]=a;return 0}
function mc(a,b,c,e){if(q)return U(16,1,a,b,c,e);a=wb.Jb(a);b=wb.Ib(a,b,c);M[e>>2]=b;return 0}function nc(a,b,c,e,h){if(q)return U(17,1,a,b,c,e,h)}function oc(a,b,c,e){if(q)return U(18,1,a,b,c,e);for(var h=0,g=0;g<c;g++){for(var k=M[b+8*g>>2],u=M[b+(8*g+4)>>2],t=0;t<u;t++){var v=G[k+t],y=vb[a];0===v||10===v?((1===a?ta:B)(Ca(y,0)),y.length=0):y.push(v)}h+=u}M[e>>2]=h;return 0}function pc(a){return 0===a%4&&(0!==a%100||0===a%400)}function qc(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}
var rc=[31,29,31,30,31,30,31,31,30,31,30,31],sc=[31,28,31,30,31,30,31,31,30,31,30,31];function tc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(pc(a.getFullYear())?rc:sc)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function uc(a,b,c,e){function h(f,r,x){for(f="number"===typeof f?f.toString():f||"";f.length<r;)f=x[0]+f;return f}function g(f,r){return h(f,r,"0")}function k(f,r){function x(P){return 0>P?-1:0<P?1:0}var H;0===(H=x(f.getFullYear()-r.getFullYear()))&&0===(H=x(f.getMonth()-r.getMonth()))&&(H=x(f.getDate()-r.getDate()));return H}function u(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function t(f){f=tc(new Date(f.Y+1900,0,1),f.Sa);var r=new Date(f.getFullYear()+1,0,4),x=u(new Date(f.getFullYear(),0,4));r=u(r);return 0>=k(x,f)?0>=k(r,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var v=M[e+40>>2];e={Bb:M[e>>2],Ab:M[e+4>>2],Qa:M[e+8>>2],Ka:M[e+12>>2],Ga:M[e+16>>2],Y:M[e+20>>2],Ra:M[e+24>>2],Sa:M[e+28>>2],Sb:M[e+32>>2],zb:M[e+36>>
2],Cb:v?F(v):""};c=F(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var y in v)c=c.replace(new RegExp(y,"g"),v[y]);var O="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
J="January February March April May June July August September October November December".split(" ");v={"%a":function(f){return O[f.Ra].substring(0,3)},"%A":function(f){return O[f.Ra]},"%b":function(f){return J[f.Ga].substring(0,3)},"%B":function(f){return J[f.Ga]},"%C":function(f){return g((f.Y+1900)/100|0,2)},"%d":function(f){return g(f.Ka,2)},"%e":function(f){return h(f.Ka,2," ")},"%g":function(f){return t(f).toString().substring(2)},"%G":function(f){return t(f)},"%H":function(f){return g(f.Qa,
2)},"%I":function(f){f=f.Qa;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":function(f){return g(f.Ka+qc(pc(f.Y+1900)?rc:sc,f.Ga-1),3)},"%m":function(f){return g(f.Ga+1,2)},"%M":function(f){return g(f.Ab,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.Qa&&12>f.Qa?"AM":"PM"},"%S":function(f){return g(f.Bb,2)},"%t":function(){return"\t"},"%u":function(f){return f.Ra||7},"%U":function(f){var r=new Date(f.Y+1900,0,1),x=0===r.getDay()?r:tc(r,7-r.getDay());f=new Date(f.Y+1900,f.Ga,f.Ka);return 0>
k(x,f)?g(Math.ceil((31-x.getDate()+(qc(pc(f.getFullYear())?rc:sc,f.getMonth()-1)-31)+f.getDate())/7),2):0===k(x,r)?"01":"00"},"%V":function(f){var r=new Date(f.Y+1901,0,4),x=u(new Date(f.Y+1900,0,4));r=u(r);var H=tc(new Date(f.Y+1900,0,1),f.Sa);return 0>k(H,x)?"53":0>=k(r,H)?"01":g(Math.ceil((x.getFullYear()<f.Y+1900?f.Sa+32-x.getDate():f.Sa+1-x.getDate())/7),2)},"%w":function(f){return f.Ra},"%W":function(f){var r=new Date(f.Y,0,1),x=1===r.getDay()?r:tc(r,0===r.getDay()?1:7-r.getDay()+1);f=new Date(f.Y+
1900,f.Ga,f.Ka);return 0>k(x,f)?g(Math.ceil((31-x.getDate()+(qc(pc(f.getFullYear())?rc:sc,f.getMonth()-1)-31)+f.getDate())/7),2):0===k(x,r)?"01":"00"},"%y":function(f){return(f.Y+1900).toString().substring(2)},"%Y":function(f){return f.Y+1900},"%z":function(f){f=f.zb;var r=0<=f;f=Math.abs(f)/60;return(r?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Cb},"%%":function(){return"%"}};for(y in v)c.includes(y)&&(c=c.replace(new RegExp(y,"g"),v[y](e)));y=vc(c);if(y.length>
b)return 0;K.set(y,a);return y.length-1}function wc(a){try{a()}catch(b){A(b)}}var Y=0,Z=null,xc=0,yc=[],zc={},Ac={},Bc=0,Cc=null,Dc=[],Ec=[];function Fc(a){var b={},c;for(c in a)(function(e){var h=a[e];b[e]="function"===typeof h?function(){yc.push(e);try{return h.apply(null,arguments)}finally{if(!ya){var g=yc.pop();assert(g===e);Z&&1===Y&&0===yc.length&&(R+=1,Y=0,wc(d._asyncify_stop_unwind),"undefined"!==typeof Fibers&&Fibers.Tb(),Cc&&(Cc(),Cc=null))}}}:h})(c);return b}
function Gc(){var a=T(4108),b=a+12;M[a>>2]=b;M[a+4>>2]=b+4096;b=yc[0];var c=zc[b];void 0===c&&(c=Bc++,zc[b]=c,Ac[c]=b);M[a+8>>2]=c;return a}function Hc(){var a=d.asm[Ac[M[Z+8>>2]]];--R;return a()}
function Ic(a){if(!ya){if(0===Y){var b=!1,c=!1;a(function(e){if(!ya&&(xc=e||0,b=!0,c)){Y=2;wc(function(){d._asyncify_start_rewind(Z)});"undefined"!==typeof Browser&&Browser.Va.ab&&Browser.Va.resume();var h=Hc();Z||(e=Dc,Dc=[],e.forEach(function(g){g(h)}))}});c=!0;b||(Y=1,Z=Gc(),wc(function(){d._asyncify_start_unwind(Z)}),"undefined"!==typeof Browser&&Browser.Va.ab&&Browser.Va.pause())}else 2===Y?(Y=0,wc(d._asyncify_stop_rewind),fb(Z),Z=null,Ec.forEach(function(e){V(e)})):A("invalid state: "+Y);return xc}}
function Jc(a){return Ic(function(b){a().then(b)})}q||(Sb(function(a){Tb=a;Ta()},function(){Tb=!1;Ta()}),"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Sa());var Kc=[null,function(a,b){if(q)return U(1,1,a,b)},xb,yb,zb,Ab,Cb,Db,Eb,Fb,Hb,Pb,ic,jc,kc,lc,mc,nc,oc];function vc(a){var b=Array(Da(a)+1);I(a,b,0,b.length);return b}
var Oc={c:function(a,b,c,e){A("Assertion failed: "+F(a)+", at: "+[b?F(b):"unknown filename",c,e?F(e):"unknown function"])},I:function(a,b){Lc(a,b)},u:function(a,b){l.Xa.push(function(){dynCall_vi.apply(null,[a,b])})},Q:function(a,b,c,e){if("undefined"===typeof SharedArrayBuffer)return B("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return B("pthread_create called with a null thread pointer!"),28;var h=[];if(q&&0===h.length)return Mc(687865856,a,b,c,
e);var g=0,k=0;if(b&&-1!=b){var u=M[b>>2];u+=81920;g=M[b+8>>2];k=0!==M[b+12>>2]}else u=2097152;(b=0==g)?g=Bb(16,u):(g-=u,assert(0<g));for(var t=T(228),v=0;57>v;++v)N[(t>>2)+v]=0;M[a>>2]=t;M[t+12>>2]=t;a=t+152;M[a>>2]=a;c={Ea:g,Fa:u,Ta:b,detached:k,wb:c,Oa:t,Ia:e,Db:h};return q?(c.Fb="spawnThread",postMessage(c,h),0):ib(c)},O:function(a){q?l.gb(a):(l.eb(),jb(a));throw"unwind";},P:function(a,b){return rb(a,b)},i:xb,H:yb,w:zb,C:function(){B("warning: unsupported syscall: __sys_madvise1");return 0},E:Ab,
F:Cb,j:Db,G:Eb,m:function(a){delete Rb[a-1]},T:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(q)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=l.Aa[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:Fb,A:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=nb();else return M[Nc()>>2]=28,-1;M[b>>2]=a/1E3|0;M[b+4>>2]=a%1E3*1E6|0;return 0},n:function(a,b,c){Gb.length=0;var e;for(c>>=2;e=G[b++];)(e=105>e)&&c&1&&c++,
Gb.push(e?Ia[c++>>1]:M[c]),++c;return Xa[a].apply(null,Gb)},z:qb,l:function(){},D:Hb,d:pb,e:Za,g:nb,q:function(a,b,c){G.copyWithin(a,b,b+c)},K:function(a,b,c){Kb.length=b;c>>=3;for(var e=0;e<b;e++)Kb[e]=Ia[c+e];return(0>a?Xa[-a-1]:Kc[a]).apply(null,Kb)},r:function(){A("OOM")},L:function(a,b,c){return Mb(a)?Nb(a,b,c):Pb(a,b,c)},k:function(){},J:function(){},S:function(a,b,c){R+=1;return setTimeout(function(){--R;V(function(){dynCall_vi.apply(null,[a,c])})},b)},o:function(a,b,c,e,h){function g(w){Ub(w,
k,v,y,t)}function k(w,Rc){Vb(w,Rc.response,function(xa){--R;V(function(){r?dynCall_vi.apply(null,[r,xa]):b&&b(xa)},D)},function(xa){--R;V(function(){r?dynCall_vi.apply(null,[r,xa]):b&&b(xa)},D)})}function u(w){Ub(w,O,v,y,t)}function t(w){V(function(){P?dynCall_vi.apply(null,[P,w]):h&&h(w)},D)}function v(w){--R;V(function(){x?dynCall_vi.apply(null,[x,w]):c&&c(w)},D)}function y(w){V(function(){H?dynCall_vi.apply(null,[H,w]):e&&e(w)},D)}function O(w){--R;V(function(){r?dynCall_vi.apply(null,[r,w]):b&&
b(w)},D)}R+=1;var J=a+112,f=F(J),r=N[J+36>>2],x=N[J+40>>2],H=N[J+44>>2],P=N[J+48>>2],W=N[J+52>>2],Ea=!!(W&4),p=!!(W&32),C=!!(W&16),D=!!(W&64);if("EM_IDB_STORE"===f)f=N[J+84>>2],Vb(a,G.slice(f,f+N[J+88>>2]),O,v);else if("EM_IDB_DELETE"===f)Xb(a,O,v);else if(C){if(p)return 0;Ub(a,Ea?k:O,v,y,t)}else Wb(a,O,p?v:Ea?g:u);return a},N:function(){return Jc(async()=>{var a=await d.queue.get();const b=Da(a)+1,c=T(b);I(a,G,c,b);return c})},M:function(a,b){b>>=2;b={alpha:!!M[b],depth:!!M[b+1],stencil:!!M[b+2],
antialias:!!M[b+3],premultipliedAlpha:!!M[b+4],preserveDrawingBuffer:!!M[b+5],powerPreference:ec[M[b+6]],failIfMajorPerformanceCaveat:!!M[b+7],rb:M[b+8],Mb:M[b+9],$a:M[b+10],kb:M[b+11],Pb:M[b+12],Qb:M[b+13]};a=Mb(a);return!a||b.kb?0:ac(a,b)},t:ic,v:jc,f:function(a){jb(a)},h:kc,B:lc,y:mc,p:nc,x:oc,R:function(){l.nb()},a:E||d.wasmMemory,s:function(a,b,c,e){return uc(a,b,c,e)}};
(function(){function a(g,k){g=g.exports;g=Fc(g);d.asm=g;La.unshift(d.asm.U);l.Ya.push(d.asm.X);wa=k;q||Ta()}function b(g){a(g.instance,g.module)}function c(g){return Wa().then(function(k){return WebAssembly.instantiate(k,e)}).then(g,function(k){B("failed to asynchronously prepare wasm: "+k);A(k)})}var e={a:Oc};q||Sa();if(d.instantiateWasm)try{var h=d.instantiateWasm(e,a);return h=Fc(h)}catch(g){return B("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return va||"function"!==
typeof WebAssembly.instantiateStreaming||Ua()||"function"!==typeof fetch?c(b):fetch(S,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,e).then(b,function(k){B("wasm streaming compile failed: "+k);B("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.U).apply(null,arguments)};
var Lc=d._main=function(){return(Lc=d._main=d.asm.V).apply(null,arguments)},fb=d._free=function(){return(fb=d._free=d.asm.W).apply(null,arguments)};d._emscripten_tls_init=function(){return(d._emscripten_tls_init=d.asm.X).apply(null,arguments)};var T=d._malloc=function(){return(T=d._malloc=d.asm.Z).apply(null,arguments)};d._emscripten_current_thread_process_queued_calls=function(){return(d._emscripten_current_thread_process_queued_calls=d.asm._).apply(null,arguments)};
var cb=d._emscripten_register_main_browser_thread_id=function(){return(cb=d._emscripten_register_main_browser_thread_id=d.asm.$).apply(null,arguments)},sb=d._emscripten_main_browser_thread_id=function(){return(sb=d._emscripten_main_browser_thread_id=d.asm.aa).apply(null,arguments)},Mc=d._emscripten_sync_run_in_main_thread_4=function(){return(Mc=d._emscripten_sync_run_in_main_thread_4=d.asm.ba).apply(null,arguments)},hb=d._emscripten_main_thread_process_queued_calls=function(){return(hb=d._emscripten_main_thread_process_queued_calls=
d.asm.ca).apply(null,arguments)},Jb=d._emscripten_run_in_main_runtime_thread_js=function(){return(Jb=d._emscripten_run_in_main_runtime_thread_js=d.asm.da).apply(null,arguments)},Ob=d.__emscripten_call_on_thread=function(){return(Ob=d.__emscripten_call_on_thread=d.asm.ea).apply(null,arguments)};d._emscripten_proxy_main=function(){return(d._emscripten_proxy_main=d.asm.fa).apply(null,arguments)};
var tb=d._pthread_testcancel=function(){return(tb=d._pthread_testcancel=d.asm.ga).apply(null,arguments)},eb=d._pthread_self=function(){return(eb=d._pthread_self=d.asm.ha).apply(null,arguments)},Qb=d._pthread_exit=function(){return(Qb=d._pthread_exit=d.asm.ia).apply(null,arguments)},bb=d.__emscripten_thread_init=function(){return(bb=d.__emscripten_thread_init=d.asm.ja).apply(null,arguments)},Nc=d.___errno_location=function(){return(Nc=d.___errno_location=d.asm.ka).apply(null,arguments)},ob=d._emscripten_get_global_libc=
function(){return(ob=d._emscripten_get_global_libc=d.asm.la).apply(null,arguments)},db=d.___pthread_tsd_run_dtors=function(){return(db=d.___pthread_tsd_run_dtors=d.asm.ma).apply(null,arguments)},Ib=d.stackSave=function(){return(Ib=d.stackSave=d.asm.na).apply(null,arguments)},lb=d.stackRestore=function(){return(lb=d.stackRestore=d.asm.oa).apply(null,arguments)},Ga=d.stackAlloc=function(){return(Ga=d.stackAlloc=d.asm.pa).apply(null,arguments)},kb=d._emscripten_stack_set_limits=function(){return(kb=
d._emscripten_stack_set_limits=d.asm.qa).apply(null,arguments)},Bb=d._memalign=function(){return(Bb=d._memalign=d.asm.ra).apply(null,arguments)},dynCall_vi=d.dynCall_vi=function(){return(dynCall_vi=d.dynCall_vi=d.asm.sa).apply(null,arguments)},mb=d.dynCall_ii=function(){return(mb=d.dynCall_ii=d.asm.ta).apply(null,arguments)},dynCall_v=d.dynCall_v=function(){return(dynCall_v=d.dynCall_v=d.asm.ua).apply(null,arguments)};
d._asyncify_start_unwind=function(){return(d._asyncify_start_unwind=d.asm.va).apply(null,arguments)};d._asyncify_stop_unwind=function(){return(d._asyncify_stop_unwind=d.asm.wa).apply(null,arguments)};d._asyncify_start_rewind=function(){return(d._asyncify_start_rewind=d.asm.xa).apply(null,arguments)};d._asyncify_stop_rewind=function(){return(d._asyncify_stop_rewind=d.asm.ya).apply(null,arguments)};var gb=d.__emscripten_allow_main_runtime_queued_calls=27312,$a=d.__emscripten_main_thread_futex=1242716;
d.keepRuntimeAlive=ra;d.PThread=l;d.PThread=l;d.wasmMemory=E;d.ExitStatus=qa;var Pc;function qa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ra=function Qc(){Pc||Sc();Pc||(Ra=Qc)};
function Sc(a){function b(){if(!Pc&&(Pc=!0,d.calledRun=!0,!ya)){q||Ya(La);q||Ya(Ma);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Tc){var c=a,e=d._emscripten_proxy_main;c=c||[];var h=c.length+1,g=Ga(4*(h+1));M[g>>2]=Fa(ha);for(var k=1;k<h;k++)M[(g>>2)+k]=Fa(c[k-1]);M[(g>>2)+h]=0;e(h,g)}if(!q){if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)c=d.postRun.shift(),Na.unshift(c);Ya(Na)}}}a=a||fa;if(!(0<Pa))if(q)aa(d),q||Ya(La),postMessage({cmd:"loaded"});
else{if(!q){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Oa();Ya(Ka)}0<Pa||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}d.run=Sc;function jb(a){za=a;if(q)throw postMessage({cmd:"exitProcess",returnCode:a}),new qa(a);ra()||l.Wa();za=a;if(!ra()){l.Wa();if(d.onExit)d.onExit(a);ya=!0}ia(a,new qa(a))}if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();
var Tc=!0;d.noInitialRun&&(Tc=!1);q&&(noExitRuntime=!1,l.ob());Sc();


  return Stockfish.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Stockfish;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Stockfish; });
else if (typeof exports === 'object')
  exports["Stockfish"] = Stockfish;
